Cookie consent 15
hlxsites/ororafresh pull request #77
Opened 2023-07-10 19:17 UTC by meejain

Fix #15 

Test URLs:
- Before: https://main--ororafresh--hlxsites.hlx.page/
- After: https://cookie-consent-15--ororafresh--hlxsites.hlx.page/Drafts/Meet/

For now added the code for loading the GA + TrustArc JS scripts. Still waiting for the customer response on those JS Scripts. However we figured out the JS scripts from the page source and pour those in. Please check & validate further.

2023-07-10 19:21 UTC, meejain commented
For now added the code for loading the GA + TrustArc JS scripts. Still waiting for the customer response on those JS Scripts. However we figured out the JS scripts from the page source and pour those in. With this Cookie Preference icon came up automatically and giving us the preference window. 

With this another issue - Cookie preferences image in footer must open cookie preferences #32 is also taken care. 

Please check & validate further.

2023-07-11 16:15 UTC, meejain commented on package.json
> +    "@esm-bundle/chai": "4.3.4-fix.0",
I think these changes were the result of npm install lint that I ran on my branch. Not required as such for customer implementation.

2023-07-17 14:39 UTC, paolomoz requested changes
loadScript is already defined in lib-franklin.js so we don't ened to define it in scripts.js right?
loadConsentManager can go in delayed.js right?

and let's remove the package.json and package-lock.json changes from the PR

2023-07-18 08:02 UTC, paolomoz approved these changes

2023-07-18 10:03 UTC, merged